name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 18
        - name: Setup Chrome v112
          uses: browser-actions/setup-chrome@v1
          with:
            chrome-version: 1109227
        - name: Chrome Version check
          run: google-chrome --version
        - name: Install chromedriver
          run: npm install chromedriver --save-dev
        - name: Install
          run: npm install
        - name: Test
          run: npm run test-headless
        - uses: actions/upload-artifact@v1
          if: ${{ always() }}
          with:
            name: test-reports
            path: reports/local
