name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 18
        # - name: Setup Chrome v112
        #   uses: browser-actions/setup-chrome@v1
        #   with:
        #     chrome-version: 1109227
        - name: Chrome Version check
          run: google-chrome --version
        - name: Install chromedriver
          run: npm install chromedriver@115 --save-dev
        - name: Install
          run: npm install
        - name: Test
          run: npm run test-headless
        - uses: actions/upload-artifact@v1
          if: ${{ always() }}
          with:
            name: test-reports-${{ github.sha }}
            path: reports/local
            
        - name: Report
          uses: PavanMudigonda/allure-html-reporter-github-pages@v1.0
          if: always()
          id: allure-report
          with:
            token: ${{ secrets.DEPLOY_TOKEN }}
            WORKFLOW_ID: ci.yml
            allure_results: reports/local/allure-results
            gh_pages: gh-pages
            allure_report: allure-report
            allure_history: allure-history
  
        - name: Deploy report to Github Pages
          if: always()
          uses: peaceiris/actions-gh-pages@v2
          env:
            PERSONAL_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
            PUBLISH_BRANCH: gh-pages
            PUBLISH_DIR: allure-history
  
        - name: Post the link to the report
          if: always()
          uses: Sibz/github-status-action@v1
          with: 
              authToken: ${{secrets.DEPLOY_TOKEN}}
              context: 'Test Results Link'
              state: 'success'
              sha: ${{ github.sha }}
              target_url: https://krishnapollu.github.io/allure-html-reporter-github-pages/${{ github.run_number }}
