name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 18
        - name: Setup Chrome
          uses: browser-actions/setup-chrome@v1
          with:
            chrome-version: beta
            id: setup-chrome
        - run: |
            echo Installed chromium version: ${{ steps.setup-chrome.outputs.chrome-version }}
            ${{ steps.setup-chrome.outputs.chrome-path }} --version
        - name: Install
          run: npm install
        - name: Test
          run: npm run test
        - uses: actions/upload-artifact@v1
          if: ${{ always() }}
          with:
            name: test-reports
            path: reports/local
