name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 18
        - name: Setup Chrome
          uses: browser-actions/setup-chrome@v1
        - name: Install chromedriver
          run: npm install chromedriver
        - name: Install
          run: npm install
        - name: Test
          run: npm run test-headless
        - uses: actions/upload-artifact@v1
          if: ${{ always() }}
          with:
            name: test-reports
            path: reports/local
